services:
  api-server:
    build: ./api-server/
    ports:
      - 8000:8000
    command:
      python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api-server/app:/app
#  frontend:
#    build: ./frontend/
#    ports:
#      - 3000:3000
#    command:
#      npx vite --port 3000 --host
#    volumes:
#      - ./frontend/app:/app
      
