# Generated by Django 5.1.4 on 2024-12-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainuploader', '0002_alter_deck_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
